apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-hello-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello-container
          image: assignment04-helloapp-k8s:latest
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: "100m"  # requesting 100 milliCPU (0.1 CPU)
              memory: "128Mi"  # requesting 128 Mebibytes of memory
            limits:
              cpu: "250m"  # limiting to 250 milliCPU (0.25 CPU)
              memory: "256Mi"  # limiting to 256 Mebibytes of memory
