version: '0.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8083:8080"
    depends_on:
      - db
    networks:
      - hello_network

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    networks:
      - hello_network

networks:
  hello_network:
    driver: bridge
